
package com.soapwebservicejaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreServiceService", targetNamespace = "http://soapWebServiceJAXWS.com/", wsdlLocation = "http://localhost:8080/SOAP_WebService_JAX-WS/ScoreService?wsdl")
public class ScoreServiceService
    extends Service
{

    private final static URL SCORESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORESERVICESERVICE_EXCEPTION;
    private final static QName SCORESERVICESERVICE_QNAME = new QName("http://soapWebServiceJAXWS.com/", "ScoreServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAP_WebService_JAX-WS/ScoreService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORESERVICESERVICE_WSDL_LOCATION = url;
        SCORESERVICESERVICE_EXCEPTION = e;
    }

    public ScoreServiceService() {
        super(__getWsdlLocation(), SCORESERVICESERVICE_QNAME);
    }

    public ScoreServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORESERVICESERVICE_QNAME, features);
    }

    public ScoreServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCORESERVICESERVICE_QNAME);
    }

    public ScoreServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORESERVICESERVICE_QNAME, features);
    }

    public ScoreServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScoreInterface
     */
    @WebEndpoint(name = "ScoreServicePort")
    public ScoreInterface getScoreServicePort() {
        return super.getPort(new QName("http://soapWebServiceJAXWS.com/", "ScoreServicePort"), ScoreInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreInterface
     */
    @WebEndpoint(name = "ScoreServicePort")
    public ScoreInterface getScoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapWebServiceJAXWS.com/", "ScoreServicePort"), ScoreInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORESERVICESERVICE_EXCEPTION!= null) {
            throw SCORESERVICESERVICE_EXCEPTION;
        }
        return SCORESERVICESERVICE_WSDL_LOCATION;
    }

}
