
package com.soapwebservicejaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoreInterface", targetNamespace = "http://soapWebServiceJAXWS.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoreInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTies", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetTies")
    @ResponseWrapper(localName = "setTiesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetTiesResponse")
    public String setTies(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "resetScores", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.ResetScores")
    @ResponseWrapper(localName = "resetScoresResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.ResetScoresResponse")
    public void resetScores();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLosses", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetLosses")
    @ResponseWrapper(localName = "getLossesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetLossesResponse")
    public String getLosses();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "increaseWins", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseWins")
    @ResponseWrapper(localName = "increaseWinsResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseWinsResponse")
    public String increaseWins();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soapwebservicejaxws.Score
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setScores", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetScores")
    @ResponseWrapper(localName = "setScoresResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetScoresResponse")
    public Score setScores(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTies", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetTies")
    @ResponseWrapper(localName = "getTiesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetTiesResponse")
    public String getTies();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setLosses", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetLosses")
    @ResponseWrapper(localName = "setLossesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetLossesResponse")
    public String setLosses(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "increaseLosses", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseLosses")
    @ResponseWrapper(localName = "increaseLossesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseLossesResponse")
    public String increaseLosses();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScores", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetScores")
    @ResponseWrapper(localName = "getScoresResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetScoresResponse")
    public String getScores();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "increaseTies", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseTies")
    @ResponseWrapper(localName = "increaseTiesResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.IncreaseTiesResponse")
    public String increaseTies();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setWins", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetWins")
    @ResponseWrapper(localName = "setWinsResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.SetWinsResponse")
    public String setWins(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWins", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetWins")
    @ResponseWrapper(localName = "getWinsResponse", targetNamespace = "http://soapWebServiceJAXWS.com/", className = "com.soapwebservicejaxws.GetWinsResponse")
    public String getWins();

}
